# ╔════════════════════════╗
# ║     Kitty Config       ║
# ╚════════════════════════╝

# Font settings
font_size 11
# font_family      monospace
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

# Transparency
# background_opacity 0.75

# Theme include
include current-theme.conf
# END_KITTY_THEME

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# Enable normal mouse selection
copy_on_select yes
mouse_hide_wait -1

shell zsh 

map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+down neighboring_window down
map ctrl+up neighboring_window up 

cursor_shape beam
cursor_beam_thickness 1.8

mouse_hide_wait 3.0
detect_urls yes 

repaint_delay 10
input_delay 3 
sync_to_monitor yes 

tab_bar_style powerline

inactive_tab_background #2A1B1B
tab_active_background #3B0F0F
inactive_tab_foreground #A88C8C
tab_bar_margin_color black

map ctrl+shift+enter new_window_with_cwd 
map ctrl+shift+t new_tab_with_cwd 
map ctrl+alt+t set_tab_title 

enable_mouse_reporting no
selection_foreground #444444
selection_background #ffffff
